services:
  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    env_file: .env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  fastapi_backend:
    build: ./backend
    container_name: fastapi_backend
    env_file: .env
    restart: always
    networks:
      - traefik-public  # Traefikとの通信用
      - default         # Postgresとの通信用
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.estatelens.rule=Host(`api-lens.go-pro-world.net`)"
      - "traefik.http.routers.estatelens.entrypoints=websecure"
      - "traefik.http.routers.estatelens.tls.certresolver=lets-encrypt"
      - "traefik.http.services.estatelens.loadbalancer.server.port=8000"
      - "traefik.docker.network=traefik-public"
networks:
  traefik-public:
    external: true

volumes:
  postgres_data:
  