services:
  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    env_file: .env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: fastapi_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    tty: true
